[build]
  publish = "_site"
  [context.production]
    command = """
      curl -fsSL https://deno.land/x/install/install.sh | sh && \
      /opt/buildhome/.deno/bin/deno task build && \
      tree . > _site/jac_tree.txt
    """
  [context.deploy-preview]
    command = """
      curl -fsSL https://deno.land/x/install/install.sh | sh && \
      /opt/buildhome/.deno/bin/deno task build && \
      tree . > _site/jac_tree.txt && \
      cp headers-dev _site/_headers 
    """
  [context.branch-deploy]
    command = """
      curl -fsSL https://deno.land/x/install/install.sh | sh && \
      /opt/buildhome/.deno/bin/deno task build && \
      tree . > _site/jac_tree.txt
      cp headers-dev _site/_headers
    """    

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests; block-all-mixed-content;"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Powered-By = "Lume mixed with Blood Sweat and Tears"
    X-Custom-Header = "Rawr eSolia Tokyo"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "autoplay=(), camera=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), publickey-credentials-get=()"

[[redirects]]
from = "/*"
to = "/brb.html"
status = 200

[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

